version: '3'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cashier
    ports:
      - "5432:5432"